messagerie_homepage:
    path:     /messagerie
    defaults: { _controller: MessagerieBundle:Messagerie:messagerie }

messagerie_new:
    path:    /messagerie/new
    defaults: { _controller: MessagerieBundle:Messagerie:messagerieNew }
