user_login:
    path:    /
    defaults: { _controller: UserBundle:Security:login }

user_check:
    path:    /user/check
    defaults: { _controller: UserBundle:Security:check }

user_register:
    path:    /user/register
    defaults: { _controller: UserBundle:Registration:register }

user_home:
    path:    /user/home
    defaults: { _controller: UserBundle:Home:home }

user_friend:
    path:    /user/friend
    defaults: { _controller: UserBundle:Friend:friend }

user_parameters:
    path:    /user/parameters
    defaults: { _controller: UserBundle:Parameters:parameters }


user_show:
    path:    /user/home
    defaults: { _controller: UserBundle:Friend:showProfil }

user_profil:
    path:    /user/parameters
    defaults: { _controller: UserBundle:Parameters:parameters }

